<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>IngameScript.Tests</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="SE.CunningUtilityCore">
      <HintPath>SE.CunningUtilityCore.dll</HintPath>
    </Reference>
    <Reference Include="VRage">
      <HintPath>..\NonGameDebugLaunch\Dlls\VRage.dll</HintPath>
    </Reference>
    <Reference Include="VRage.Game">
      <HintPath>..\NonGameDebugLaunch\Dlls\VRage.Game.dll</HintPath>
    </Reference>
    <Reference Include="VRage.Math">
      <HintPath>..\NonGameDebugLaunch\Dlls\VRage.Math.dll</HintPath>
    </Reference>
    <Reference Include="Sandbox.Game">
      <HintPath>..\NonGameDebugLaunch\Dlls\Sandbox.Game.dll</HintPath>
    </Reference>
    <Reference Include="Sandbox.Common">
      <HintPath>..\NonGameDebugLaunch\Dlls\Sandbox.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="..\SE.CunningUtilityCore.Mixin\SE.CunningUtilityCore.Mixin.projitems" Label="Shared" />
</Project>
